# Site settings
title: Matthew Randall
email: your-email@example.com
description: >-
  Electrical engineering student passionate about embedded systems, signal processing, and applying technology to real-world problems.
baseurl: "" # leave this blank for user/organization pages
url: "https://matthewrandall10.github.io" # no trailing slash
github_username: MatthewRandall10

# Author settings
author:
  name: Matthew Randall
  avatar: linkedin-2.jpg
  bio: >
    Electrical Engineering student at UC Santa Cruz. Interested in embedded systems, circuit design, and technical sales.

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Permalinks
permalink: /:year/:month/:day/:title/

# Social Links (optional)
social:
  github: https://github.com/MatthewRandall10
  linkedin: https://www.linkedin.com/in/matthew-randall/
  email: matthewsrandall10@gmail.com

# Google Analytics (optional)
google_analytics: ""

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
