title: Matthew Randall
description: > # this means to ignore newlines until "baseurl:"
  Electrical engineering student passionate about embedded systems, signal processing, and applying technology to real-world problems.
permalink: ':title/'
baseurl: "" # Leave blank if using matthewrandall10.github.io directly
url: "https://matthewrandall10.github.io"
site-twitter: # Optional

# Author Settings
author: Matthew Randall
author-img: linkedin-2.jpg # Your uploaded profile image in assets/img/
about-author: Electrical Engineering student at UC Santa Cruz. Interested in embedded systems, circuit design, and technical sales.
social-twitter: 
social-facebook: 
social-github: MatthewRandall10
social-linkedin: https://www.linkedin.com/in/matthew-randall/
social-email: matthewsrandall10@gmail.com

# Disqus (optional for blog comments)
discus-identifier: # Leave blank if not using Disqus

# Tracker (optional for Google Analytics)
analytics: # Add your Google Analytics tracking ID here (e.g., G-XXXXXXXXXX)
